main/routes.py
"""
Main App Routes

"""

from flask import Blueprint, render_template, redirect, request, url_for, session
from main import util

main = Blueprint("main", __name__, template_folder = "templates")

@main.route("/")
def index():
    return render_template("/main/index.html")

@main.route("/contributors")
def contributors():
    return render_template("/main/contributors.html")

@main.route("/user_models")
def user_models():
    if "logged_in" in session and session["logged_in"]:
        return render_template("/main/user_models.html", models = util.get_user_models())

    else:
        return redirect(url_for( "auth.login" ))

@main.route("/upload_images", methods = ["GET", "POST"])
def upload_images():
    if "id" not in session or not session["id"]:
        util.create_session()

    if request.method == "POST":
        util.upload_images(request.files.getlist("image-file-input"))

        return redirect(url_for( "main.select_model" ))

    else:
        return render_template("/main/upload_images.html")

@main.route("/select_model")
def select_model():
    if not "images_uploaded" in session or not session["images_uploaded"]:
        return redirect(url_for( "main.upload_images" ))

    else:
        if "logged_in" in session and session["logged_in"]:
            return render_template("/main/select_model.html", models = util.get_user_models())
        
        else:
            return redirect(url_for( "main.classifying_images", model = "default" ))


@main.route("/classifying_images/<string:model>")
def classifying_images(model):
    if (not "images_uploaded" in session or not session["images_uploaded"]):
        return redirect(url_for( "main.upload_images" ))
    
    else:
        return render_template("main/classifying_images.html", model = model)

@main.route("/classify_images/<string:model>")
def classify_images(model):
    util.classify_images(model)
    
    return "Done"

@main.route("/classified_images")
def classified_images():
    return render_template("main/classified_images.html")

@main.route("/record_corrections", methods = ["POST"])
def record_corrections():
    util.record_corrections(request.form)

    return redirect(url_for( "main.set_prediction_accuracy" ))

@main.route("/set_prediction_accuracy")
def set_prediction_accuracy():
    util.set_prediction_accuracy()

    return redirect(url_for( "main.model_insights" ))

@main.route("/model_insights")
def model_insights():   
    return render_template("/main/model_insights.html")

@main.route("/model_insights_from_id/<string:model_id>")
def model_insights_from_id(model_id):
    util.get_model_insights_from_cloud(model_id) if model_id != "default" else False

    util.set_model_path(model_id)

    return render_template("/main/model_insights.html")

@main.route("/tune_model", methods=["GET", "POST"])
def tune_model():
    if "logged_in" in session and session["logged_in"]:
        if request.method == "POST":
            util.set_model_layers(request.form)

            return render_template("main/tuning_model.html")
        
        else:
            from main.util import ACTIVATION_FUNCTIONS
            from main.util import OPTIMIZATION_FUNCTIONS
            from main.util import LOSS_FUNCTIONS

            return render_template("/main/tune_model.html", activation_functions = ACTIVATION_FUNCTIONS, optimization_functions = OPTIMIZATION_FUNCTIONS, loss_functions = LOSS_FUNCTIONS)

    else:
        return redirect(url_for( "auth.login" ))

@main.route("/train_model")
def train_model():
    model, trained_model = util.train_model()
    
    util.save_model_local(model)
    util.save_model_accuracy_local(trained_model)
    util.save_model_loss_local(trained_model)

    return "Done"

@main.route("/trained_model")
def trained_model():
    return render_template("/main/trained_model.html")

@main.route("/saving_model")
def saving_model():
    if "predictions" in session:
        del session["predictions"]

    return render_template("/main/saving_model.html")

@main.route("/save_model")
def save_model():
    util.save_model_to_cloud()

    util.finish_classification()
    
    return "Done"

@main.route("/finish_classification")
def finish_classification():
    util.finish_classification()

    return redirect(url_for( "main.index" ))

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Prajas Kadepurkar | Elton Lemos | Abhishek Ghoshal | Tanmey Saraiya">

    <link rel="stylesheet" href="{{url_for( 'static', filename = 'css/style.css' )}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
    
    <title>Image Classification Playground | {{title}}</title>
</head>
<body>
    <div class="container">
        <nav class="navbar">
            <a href="{{url_for( 'main.index' )}}" class="logo">
                <i class="far fa-images"></i>
                <span>Image Classification Playground</span>
            </a>

            <ul>
                <li>
                    <a href="{{url_for( 'main.contributors' )}}" class="{{ 'active' if active == 'contributors' else '' }}">Contributors</a>
                </li>

                <li>
                    <a href="{{url_for( 'main.upload_images' )}}" class="{{ 'active' if active == 'classify_images' else '' }}">Classify Images</a>
                </li>

                {% if "logged_in" in session and session["logged_in"] %}

                    <li>
                        <a href="{{url_for( 'main.user_models' )}}">My Models</a>
                    </li>

                    <li>
                        <a href="{{url_for( 'auth.logout' )}}">Logout</a>
                    </li>

                {% else %}
                    <li>
                        <a href="{{url_for( 'auth.login' )}}" class="{{ 'active' if active == 'login' else '' }}">Login</a>
                    </li>

                    <li>
                        <a href="{{url_for( 'auth.sign_up' )}}" class="{{ 'active' if active == 'sign_up' else '' }}">Sign Up</a>
                    </li>
                {% endif %}

            </ul>
        </nav>

        <nav class="mobile-nav">
            <a href="{{url_for( 'main.index' )}}" class="logo">
                <i class="far fa-images"></i>
                <span>Image Classification Playground</span>
            </a>

            <i class="fas fa-bars" id="sidebar-toggle"></i>
        </nav>

        <div class="sidebar">
            <ul>
                <li>
                    <a href="{{url_for( 'main.contributors' )}}" class="{{ 'active' if active == 'contributors' else '' }}">Contributors</a>
                </li>

                <li>
                    <a href="{{url_for( 'main.upload_images' )}}" class="{{ 'active' if active == 'classify_images' else '' }}">Classify Images</a>
                </li>

                {% if "logged_in" in session and session["logged_in"] %}

                    <li>
                        <a href="{{url_for( 'main.user_models' )}}">My Models</a>
                    </li>

                    <li>
                        <a href="{{url_for( 'auth.logout' )}}">Logout</a>
                    </li>

                {% else %}
                    <li>
                        <a href="{{url_for( 'auth.login' )}}" class="{{ 'active' if active == 'login' else '' }}">Login</a>
                    </li>

                    <li>
                        <a href="{{url_for( 'auth.sign_up' )}}" class="{{ 'active' if active == 'sign_up' else '' }}">Sign Up</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    
        {% block body %}
        {% endblock %}
    </div>

    <script src="{{url_for( 'static', filename = 'js/mobile_nav.js' )}}"></script>
</body>
</html>

main/templates/main/classified_images.html
{% extends "main/base.html" %}
{% set title = "Predictions" %}
{% set active = "classify_images" %}

{% block body %}

    <form action="{{url_for( 'main.record_corrections' )}}" method="POST">

        <div class="card-grid" id="classified-images">

            {% for image in session["predictions"] %}

                <div class="card">
                    <img src="{{url_for('static', filename = 'uploads/temp/' + session['id'] + '/' + image)}}" alt="{{image}}">
                    <select name="{{image}}">
                        <option value="{{session['predictions'][image]}}" selected>{{session["predictions"][image]}}</option>
                        <option value="Buildings">Buildings</option>
                        <option value="Forest">Forest</option>
                        <option value="Glacier">Glacier</option>
                        <option value="Mountain">Mountain</option>
                        <option value="Sea">Sea</option>
                        <option value="Street">Street</option>
                    </select>
                </div>

            {% endfor %}

        </div>

        <button class="button" id="next-step">Next</button>
    </form>    

{% endblock %}

main/templates/main/classifying_images.html
{% extends "main/base.html" %}
{% set active = "classify_images" %}
{% set title = "Classifying Images" %}

{% block body %}

    <div class="loading">
        
        <img src="{{url_for( 'static', filename = 'images/gear.svg' )}}" alt="Loading">
        <p>Classifying Your Images. Please Wait...</p>

    </div>

    <script>
        classification_url = "/classify_images/{{model}}";
    </script>
    <script src="{{url_for( 'static', filename = 'js/main/classify_images.js' )}}"></script>

{% endblock %}

main/templates/main/contributors.html
{% extends "main/base.html" %}
{% set title = "Contributors" %}
{% set active = "contributors" %}
{% block body %}

<h2 style="text-align: center;">Meet the Contributors</h2>

<div class="card-grid" id="contributors">
    <div class="card">
        <img src="{{url_for( 'static', filename = 'images/contributors/prajas.jpg' )}}" alt="Prajas Kadepurkar">
        <p class="name">Prajas Kadepurkar</p>
        <p class="role">Full Stack Web Development</p>
        <div class="links">
            <a href="https://www.linkedin.com/in/prajask/">
                <i class="fab fa-linkedin"></i>
            </a>

            <a href="https://github.com/prajask">
                <i class="fab fa-github"></i>
            </a>
        </div>
    </div>

    <div class="card">
        <img src="{{url_for( 'static', filename = 'images/contributors/elton.jpg' )}}" alt="Elton Lemos">
        <p class="name">Elton Lemos</p>
        <p class="role">AI / ML Development</p>
        <div class="links">
            <a href="https://www.linkedin.com/in/elton-lemos/">
                <i class="fab fa-linkedin"></i>
            </a>

            <a href="https://github.com/icefrostpeng">
                <i class="fab fa-github"></i>
            </a>
        </div>
    </div>

    <div class="card">
        <img src="{{url_for( 'static', filename = 'images/contributors/abhishek.jpeg' )}}" alt="Abhishek Ghoshal">
        <p class="name">Abhishek Ghoshal</p>
        <p class="role">AI / ML Development</p>
        <div class="links">
            <a href="https://www.linkedin.com/in/abhishek-ghoshal-0a0ab613/">
                <i class="fab fa-linkedin"></i>
            </a>

            <a href="https://github.com/abhighosh98">
                <i class="fab fa-github"></i>
            </a>
        </div>
    </div>

    <div class="card">
        <img src="{{url_for( 'static', filename = 'images/contributors/tanmey.jpeg' )}}" alt="Tanmey Saraiya">
        <p class="name">Tanmey Saraiya</p>
        <p class="role">Front End Web Development</p>
        <div class="links">
            <a href="https://www.linkedin.com/in/tanmey-saraiya-bab59016a/">
                <i class="fab fa-linkedin"></i>
            </a>

            <a href="https://github.com/TanmeySaraiya">
                <i class="fab fa-github"></i>
            </a>
        </div>
    </div>
</div>    

{% endblock %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% set title = "Home" %}

{% block body %}

    <section class="showcase">
        <div>
            <img src="{{url_for( 'static', filename = 'images/showcase/classify_images.png' )}}" alt="">
            <p class="title">Classify Images</p>
        </div>
        
        <div>
            <img src="{{url_for( 'static', filename = 'images/showcase/train_model.png' )}}" alt="">
            <p class="title">Tune Your Own Models</p>
        </div>
        
        <div>
            <img src="{{url_for( 'static', filename = 'images/showcase/model_insights.png' )}}" alt="">
            <p class="title">View Model Insights</p>
        </div>
    </section>

    {% if "logged_in" in session and session["logged_in"] %}
        <a href="{{url_for( 'main.upload_images' )}}" class="sign-up button">Get Started</a>
    {% else%}
        <a href="{{url_for( 'auth.sign_up' )}}" class="sign-up button">Sign Up</a>

        <a href="{{url_for( 'main.upload_images' )}}" class="guest">
            Or Get Started as a Guest
            <i class="fas fa-chevron-right"></i>
        </a>
    {% endif %}

{% endblock %}

main/templates/main/model_insights.html
{% extends "main/base.html" %}
{% set title = "Model Insights" %}
{% set active = "classify_images" %}

{% block body %}

    <div class="card-grid" id="model-insights">
        {% if "predictions" in session %}
            <div class="card model-accuracy">
                <p class="title">Current Prediction Accuracy</p>

                <p>
                    <span>Images Provided: </span>
                    {{session["number_of_images"]}} Images
                </p>

                <p>
                    <span>Correct Predictions: </span>
                    {{session["number_of_images"] - session["number_of_corrections"]}}
                </p>

                <p>
                    <span>Accuracy: </span>
                </p>

                <div class="accuracy-bar">
                    <div class="border">
                        <p>
                            {{session["prediction_accuracy"]}} %
                        </p>
                    </div>

                    <div class="bar"></div>

                    <script>
                        const accuracy_bar_border = document.querySelector(".border");
                        const accuracy_bar = document.querySelector(".bar");

                        if("{{session['prediction_accuracy']}}" < 50){
                            accuracy_bar_border.style.border = "2px solid #FF333A";
                            accuracy_bar.style.background = "#FF333A";
                        }

                        else{
                            accuracy_bar_border.style.border = "2px solid #8AC926";
                            accuracy_bar.style.background = "#8AC926";
                        }   

                        accuracy_bar.style.width = "{{session['prediction_accuracy']}}%";
                    </script>
                </div>
            </div>
        {% endif %}

        <div class="card model-accuracy">
            <p class="title">Model Training and Validation Accuracy</p>

            <img src="{{url_for( 'static', filename = session['model_path'] + '/model_accuracy.png' )}}" alt="Model Training and Validation Accuracy Graph">
        </div>

        <div class="card model-accuracy">
            <p class="title">Model Training and Validation Loss</p>

            <img src="{{url_for( 'static', filename = session['model_path'] + '/model_loss.png' )}}" alt="Model Training and Validation Loss Graph">
        </div>
    </div>

    {% if "logged_in" in session and session["logged_in"] and "predictions" in session %}

        <div class="button-grid">
            <a href="{{ url_for( 'main.tune_model' ) }}" class="button">Tune Model</a>
            <a href="{{url_for( 'main.finish_classification' )}}" class="button">Finish</a>
        </div>
    
    {% elif "predictions" in session %}

        <a href="{{url_for( 'main.finish_classification' )}}" class="button" id="next-step">Finish</a>

    {% endif %}

{% endblock %}

main/templates/main/saving_model.html
{% extends "main/base.html" %}
{% set active = "classify_images" %}
{% set title = "Classifying Images" %}

{% block body %}

    <div class="loading">
        
        <img src="{{url_for( 'static', filename = 'images/gear.svg' )}}" alt="Loading">
        <p>Saving Your Model. Please Wait...</p>

    </div>

    <script>
        classification_url = "/classify_images/{{model}}";
    </script>
    <script src="{{url_for( 'static', filename = 'js/main/tune_model/save_model.js' )}}"></script>

{% endblock %}

main/templates/main/select_model.html
{% extends "/main/base.html" %}
{% set title = "Select Model" %}
{% set active = "classify_images" %}

{% block body %}

<h2>Select a Model to Classify Images</h2>

<div class="card-grid" id="models">
    <div class="card">
        <p class="name">Default Model</p>
        
        <div class="links">

            <a href="{{url_for( 'main.model_insights_from_id', model_id = 'default' )}}" class="model-insights" target="_blank">
                View Model Insights
                <i class="fas fa-chevron-right"></i>
            </a>

            <a href="{{url_for( 'main.classifying_images', model = 'default' )}}" class="select-model">
                Select Model
                <i class="fas fa-chevron-right"></i>
            </a>
            
        </div>
    </div>

    {% for model in models %}
        <div class="card">
            <p class="name">{{models[model]}}</p>

            <div class="links">

                <a href="{{url_for( 'main.model_insights_from_id', model_id = model )}}" class="model-insights" target="_blank">
                    View Model Insights
                    <i class="fas fa-chevron-right"></i>
                </a>

                <a href="{{url_for( 'main.classifying_images', model = model )}}" class="select-model">
                    Select Model
                    <i class="fas fa-chevron-right"></i>
                </a>

            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

main/templates/main/trained_model.html
{% extends "main/base.html" %}
{% set active = "classify_images" %}
{% set title = "Trained Model" %}

{% block body %}

    <div class="card-grid" id="model-insights">
        <div class="card model-accuracy">
            <p class="title">Model Name</p>
            <p class="title">{{session["temp_model_name"]}}</p>
        </div>

        <div class="card model-accuracy">
            <p class="title">Model Training and Validation Accuracy</p>

            <img src="{{url_for( 'static', filename = 'models/temp/' + session['id'] + '/' + session['temp_model_id'] + '/model_accuracy.png' )}}" alt="Model Training and Validation Accuracy Graph">
        </div>

        <div class="card model-accuracy">
            <p class="title">Model Training and Validation Loss</p>

            <img src="{{url_for( 'static', filename = 'models/temp/' + session['id'] + '/' + session['temp_model_id'] + '/model_loss.png' )}}" alt="Model Training and Validation Loss Graph">
        </div>
    </div>

    <div class="button-grid">
        <a href="/saving_model" class="button">Save Model</a>
        <a href="/finish_classification" class="button">Finish</a>
    </div>

{% endblock %}

main/templates/main/tuning_model.html
{% extends "main/base.html" %}
{% set active = "classify_images" %}
{% set title = "Tuning Model" %}

{% block body %}

    <div class="loading">
            
        <img src="{{url_for( 'static', filename = 'images/gear.svg' )}}" alt="Loading">
        <p>Tuning Your Model. This Might Take a While... Please Wait...</p>

    </div>

    <script src="{{url_for( 'static', filename = 'js/main/tune_model/train_model.js' )}}"></script>

{% endblock %}

main/templates/main/upload_images.html
{% extends "main/base.html" %}
{% set title = "Upload Images" %}
{% set active = "classify_images" %}

{% block body %}

    <form action="{{url_for('main.upload_images')}}" method="POST" enctype="multipart/form-data" class="file-form" id="file-input-form">
        <label for="image-file-input" class="file-input-label">
            <i class="fas fa-upload"></i>
            <p id="input-label-text">Drag and Drop Images or Browse</p>
        </label>
        <input id="image-file-input" name="image-file-input" class="image-file-input" type="file" accept="image/*" multiple required/>

        <button class="button" type="button" onclick="validate()">Next</button>
    </form>

    <script src="{{url_for( 'static', filename = 'js/main/upload_images.js' )}}"></script>

{% endblock %}

main/templates/main/user_models.html
{% extends "main/base.html" %}
{% set active = "user_models" %}
{% set title = "My Models" %}

{% block body %}

    <div class="card-grid" id="models">

        <div class="card">
            <p class="name">Default Model</p>
            
            <div class="links">
    
                <a href="{{url_for( 'main.model_insights_from_id', model_id = 'default' )}}" class="model-insights" target="_blank">
                    View Model Insights
                    <i class="fas fa-chevron-right"></i>
                </a>
                
            </div>
        </div>
    
        {% for model in models %}
            <div class="card">
                <p class="name">{{models[model]}}</p>
    
                <div class="links">
    
                    <a href="{{url_for( 'main.model_insights_from_id', model_id = model )}}" class="model-insights" target="_blank">
                        View Model Insights
                        <i class="fas fa-chevron-right"></i>
                    </a>
    
                </div>
            </div>
        {% endfor %}

    </div>

{% endblock %}